version: '2'

services:

  sdr_db:
    container_name: sdr_db
    image: mdillon/postgis
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5433:5432

  sdr_service:
    container_name: sdr_service
    build:
        context: .
        dockerfile: Dockerfile
    image: wcs/sdr_service:latest
    volumes:
      - $PWD/src:/var/projects/webapp
    ports:
      - 8080:8080
      - 80:80
    env_file:
      - .env
    links:
      - sdr_db
