# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('species', '0014_species_composite_habitat'),
        ('base', '0006_auto_20181027_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinitionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementid', models.DecimalField(decimal_places=2, max_digits=7, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('spatially_explicit', models.BooleanField(default=True)),
                ('mapped_manually', models.BooleanField(default=False)),
                ('native_units', models.BooleanField(default=False)),
                ('subset_rule', models.CharField(blank=True, help_text='operands: [element_id]; operators: +-/*<>== logical_and() logical_or()', max_length=255)),
                ('adjacency_rule', models.IntegerField(blank=True, help_text='Within x m (integer)', null=True)),
                ('description', models.TextField(blank=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('definitiontype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='muirweb.DefinitionType', verbose_name='subject type')),
            ],
        ),
        migrations.CreateModel(
            name='FrequencyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('maxprob', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'relationship type',
            },
        ),
        migrations.CreateModel(
            name='GroupLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'relationship type label',
            },
        ),
        migrations.CreateModel(
            name='InteractionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('interactiontype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='muirweb.InteractionType')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_relationships', to='muirweb.Element')),
                ('relationshiptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muirweb.Group')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StateLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrengthType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prob', models.SmallIntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='muirweb.StateLabel'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muirweb.State'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='strengthtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='muirweb.StrengthType'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_relationships', to='muirweb.Element'),
        ),
        migrations.AddField(
            model_name='group',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='muirweb.GroupLabel'),
        ),
        migrations.AddField(
            model_name='element',
            name='frequencytype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='muirweb.FrequencyType'),
        ),
        migrations.AddField(
            model_name='element',
            name='references',
            field=models.ManyToManyField(blank=True, to='base.Reference'),
        ),
        migrations.AddField(
            model_name='element',
            name='species',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element', to='species.Species'),
        ),
    ]
