# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='reference',
            name='year',
        ),
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(max_length=255, verbose_name='reference'),
        ),
    ]
