# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20181014_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='year_end',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='end year'),
        ),
        migrations.AddField(
            model_name='period',
            name='year_start',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='start year'),
        ),
    ]
