# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20181015_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['year_start', 'year_end', 'name']},
        ),
    ]
