# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20181015_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='year_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='end year'),
        ),
        migrations.AlterField(
            model_name='period',
            name='year_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='start year'),
        ),
    ]
