# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 22:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sdr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('pagenumbers', models.CharField(max_length=255, verbose_name='page numbers')),
            ],
            options={
                'ordering': ['sdr'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Laterdev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laterdev', models.TextField()),
                ('pagenumbers', models.CharField(max_length=255, verbose_name='page numbers')),
            ],
            options={
                'verbose_name': 'later development',
                'verbose_name_plural': 'later developments',
                'ordering': ['sdr'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('pagenumbers', models.CharField(max_length=255, verbose_name='page numbers')),
            ],
            options={
                'ordering': ['sdr'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('areas', models.ManyToManyField(to='sdr.DefArea')),
                ('featuretype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdr.DefFeatureType', verbose_name='feature type')),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='PlaceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(geography=True, srid=4326)),
                ('pagenumbers', models.CharField(max_length=255, verbose_name='page numbers')),
                ('canonical', models.BooleanField(default=False)),
                ('invented', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pn.Place')),
                ('sdr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdr.Sdr', verbose_name='SDR')),
            ],
            options={
                'verbose_name': 'place line',
                'verbose_name_plural': 'place lines',
                'ordering': ['line__name'],
            },
        ),
        migrations.CreateModel(
            name='Placename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='placename')),
                ('pagenumbers', models.CharField(max_length=255, verbose_name='page numbers')),
                ('canonical', models.BooleanField(default=False)),
                ('invented', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pn.Language', verbose_name='language')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pn.Place')),
                ('sdr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdr.Sdr', verbose_name='SDR')),
            ],
            options={
                'verbose_name': 'placename',
                'verbose_name_plural': 'placenames',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlacePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(geography=True, srid=4326)),
                ('pagenumbers', models.CharField(max_length=255, verbose_name='page numbers')),
                ('canonical', models.BooleanField(default=False)),
                ('invented', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pn.Place')),
                ('sdr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdr.Sdr', verbose_name='SDR')),
            ],
            options={
                'verbose_name': 'place point',
                'verbose_name_plural': 'place points',
                'ordering': ['point__name'],
            },
        ),
        migrations.CreateModel(
            name='PlacePolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326)),
                ('pagenumbers', models.CharField(max_length=255, verbose_name='page numbers')),
                ('canonical', models.BooleanField(default=False)),
                ('invented', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pn.Place')),
                ('sdr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdr.Sdr', verbose_name='SDR')),
            ],
            options={
                'verbose_name': 'place polygon',
                'verbose_name_plural': 'place polygons',
                'ordering': ['polygon__name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pn.Place'),
        ),
        migrations.AddField(
            model_name='location',
            name='sdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdr.Sdr', verbose_name='SDR'),
        ),
        migrations.AddField(
            model_name='laterdev',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pn.Place'),
        ),
        migrations.AddField(
            model_name='laterdev',
            name='sdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdr.Sdr', verbose_name='SDR'),
        ),
        migrations.AddField(
            model_name='description',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pn.Place'),
        ),
        migrations.AddField(
            model_name='description',
            name='sdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdr.Sdr', verbose_name='SDR'),
        ),
    ]
