# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-09 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeline',
            options={'verbose_name': 'place line', 'verbose_name_plural': 'place lines'},
        ),
        migrations.AlterModelOptions(
            name='placepoint',
            options={'verbose_name': 'place point', 'verbose_name_plural': 'place points'},
        ),
        migrations.AlterModelOptions(
            name='placepolygon',
            options={'verbose_name': 'place polygon', 'verbose_name_plural': 'place polygons'},
        ),
    ]
