# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-11 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pn', '0002_auto_20180309_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='related_places',
            field=models.ManyToManyField(related_name='_place_related_places_+', to='pn.Place'),
        ),
    ]
