# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sdr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefAccuracyGeoref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'georeferencing accuracy level',
                'verbose_name_plural': 'georeferencing accuracy levels',
            },
        ),
        migrations.CreateModel(
            name='DefAccuracyLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'location accuracy level',
                'verbose_name_plural': 'location accuracy levels',
            },
        ),
        migrations.CreateModel(
            name='DefAccuracySize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'size accuracy level',
                'verbose_name_plural': 'size accuracy levels',
            },
        ),
        migrations.CreateModel(
            name='DefArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DefFeatureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'feature type',
                'verbose_name_plural': 'feature types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DefRectification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'rectification order',
                'verbose_name_plural': 'rectification orders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DefResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'resolution quality level',
                'verbose_name_plural': 'resolution quality levels',
            },
        ),
        migrations.CreateModel(
            name='DefType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'resource type',
                'verbose_name_plural': 'resource types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=sdr.models.sdrfile_name)),
                ('notes', models.TextField(blank=True)),
                ('qa_date', models.DateField(blank=True, null=True, verbose_name='QA date')),
                ('final', models.BooleanField(default=False)),
                ('featuretype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdr.DefFeatureType', verbose_name='feature type')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='features_processed', to=settings.AUTH_USER_MODEL, verbose_name='processed by')),
                ('qa_processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="QA'd by")),
            ],
            options={
                'verbose_name': 'digitized feature',
                'verbose_name_plural': 'digitized features',
                'ordering': ['sdr'],
            },
        ),
        migrations.CreateModel(
            name='Georef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=sdr.models.sdrfile_name)),
                ('control_points', models.SmallIntegerField()),
                ('rms_error', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='RMS error')),
                ('notes', models.TextField(blank=True)),
                ('qa_date', models.DateField(blank=True, null=True, verbose_name='QA date')),
                ('final', models.BooleanField(default=False)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='georefs_processed', to=settings.AUTH_USER_MODEL, verbose_name='processed by')),
                ('qa_processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="QA'd by")),
                ('rectification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdr.DefRectification')),
            ],
            options={
                'verbose_name': 'georeferenced image',
                'verbose_name_plural': 'georeferenced images',
                'ordering': ['sdr'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=sdr.models.sdrfile_name)),
                ('notes', models.TextField(blank=True)),
                ('qa_date', models.DateField(blank=True, null=True, verbose_name='QA date')),
                ('final', models.BooleanField(default=False)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans_processed', to=settings.AUTH_USER_MODEL, verbose_name='processed by')),
                ('qa_processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="QA'd by")),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdr.DefResolution')),
            ],
            options={
                'verbose_name': 'scanned image',
                'verbose_name_plural': 'scanned images',
                'ordering': ['sdr'],
            },
        ),
        migrations.CreateModel(
            name='Sdr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zotero', models.CharField(max_length=8, verbose_name='zotero ID')),
                ('name_short', models.CharField(max_length=255, verbose_name='short name')),
                ('sdr_year', models.SmallIntegerField(verbose_name='earliest year depicted')),
                ('notes', models.TextField(blank=True)),
                ('notes_sdraccloc', models.TextField(blank=True, verbose_name='location accuracy notes')),
                ('notes_sdraccsiz', models.TextField(blank=True, verbose_name='size accuracy notes')),
                ('notes_sdraccgeo', models.TextField(blank=True, verbose_name='georeferencing accuracy notes')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('areas', models.ManyToManyField(to='sdr.DefArea')),
                ('intended_features', models.ManyToManyField(to='sdr.DefFeatureType')),
                ('sdraccgeo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdr.DefAccuracyGeoref', verbose_name='georeferencing accuracy')),
                ('sdraccloc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdr.DefAccuracyLocation', verbose_name='location accuracy')),
                ('sdraccsiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdr.DefAccuracySize', verbose_name='size accuracy')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sdr.DefType')),
            ],
            options={
                'verbose_name': 'spatial data resource',
                'verbose_name_plural': 'spatial data resources',
                'ordering': ['-last_modified'],
            },
        ),
        migrations.AddField(
            model_name='scan',
            name='sdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdr.Sdr'),
        ),
        migrations.AddField(
            model_name='georef',
            name='sdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdr.Sdr'),
        ),
        migrations.AddField(
            model_name='feature',
            name='sdr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdr.Sdr'),
        ),
    ]
