# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20181014_1452'),
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genus',
            name='family',
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['taxon', 'name_accepted'], 'verbose_name_plural': 'species'},
        ),
        migrations.RemoveField(
            model_name='species',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='species',
            name='name',
        ),
        migrations.AddField(
            model_name='species',
            name='name_accepted',
            field=models.CharField(default='', max_length=255, verbose_name='accepted scientific name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciesreference',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='base.Period'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='species',
            name='historical_likelihood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='species.Likelihood'),
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Genus',
        ),
    ]
