# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_auto_20181014_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
    ]
