# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 18:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_species_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='col_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='', verbose_name='Catalog of Life data'),
            preserve_default=False,
        ),
    ]
