# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0004_species_col_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='name_common',
            field=models.CharField(blank=True, max_length=255, verbose_name='common name'),
        ),
    ]
