# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0005_auto_20181015_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='name_common_ref',
            field=models.CharField(blank=True, help_text='if different from COL common name', max_length=255, verbose_name='common name (reference)'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_common',
            field=models.CharField(blank=True, max_length=255, verbose_name='common name (first English COL)'),
        ),
    ]
