# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0007_auto_20181016_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesreference',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
