# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('species', '0008_speciesreference_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesreference',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
