# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 10:05
from __future__ import unicode_literals

from django.db import migrations


def merge_species(apps, schema_editor):
    species = apps.get_model('species', 'Species')
    speciesreference = apps.get_model('species', 'SpeciesReference')

    for s in species.objects.all():
        dups = species.objects.filter(col=s.col).exclude(pk=s.id)

        for d in dups:
            srs = speciesreference.objects.filter(species=d.id)
            try:
                s2 = species.objects.get(pk=s.id)
                for sr in srs:
                    sr.species = s
                    sr.save()
                    print('Changed species from {} to {} for speciesref {}'.format(d.id, s.id, sr.id))
                print('Deleting species {}'.format(d.id))
                d.delete()

            except species.DoesNotExist:
                print('{} already deleted'.format(s.id))


def cannot_split():
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('species', '0009_speciesreference_updated_by'),
    ]

    operations = [
        migrations.RunPython(merge_species, cannot_split)
    ]
