# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0010_auto_20181026_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='col',
            field=models.CharField(max_length=32, unique=True, verbose_name='Catalog of Life ID'),
        ),
    ]
