# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0011_auto_20181026_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='name_accepted_ref',
            field=models.CharField(blank=True, help_text='Enter if different from COL accepted scientific name', max_length=255, verbose_name='accepted scientific name (reference)'),
        ),
    ]
