# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0012_species_name_accepted_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name_accepted'], 'verbose_name_plural': 'species'},
        ),
    ]
